### ISSUE TITLE
Remove filters from the codebase

### ISSUE THREAD

**Issue by TomChaton** [tomcroft/tantrum_elastic#110]
- Delete the src/Filter/ directory
- Delete src/Query/Filered.php
- Delete the tests/Filter directory
- Delete tests/Query/FilteredTest.php
- Fix any test using the filtered query

**Comment by carlcasbolt** [comment]
What's the status on this? #111 was closed with no merge. Did it break something?

**Comment by TomChaton** [comment]
Need a fix to uniqid in tests first. Also, test coverage dropped, as some things were being tested as side effects.
