### ISSUE TITLE
support for _cache parameter on some elements

### ISSUE THREAD

**Issue by carlcasbolt** [tomcroft/tantrum_elastic#93]
multiple elements can use the _cache parameter so maybe we should allow this to be set as well.

e.g.
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-nested-filter.html
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-not-filter.html
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-or-filter.html
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-prefix-filter.html
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-term-filter.html
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-terms-filter.html

**Comment by TomChaton** [comment]
_cache is not supported in elasticsearch 2.0
